def sleep_s(tick:float):...

def resetTimer():...

def timer()->float:...

def stop_exit():...

def get_port_linke(port:int)->int:...

def set_port_mode(port:int,mode:float):...

def set_point_matrix(point:int,state:int):...